### ISSUE TITLE
won't compile without native feature

### ISSUE THREAD

**Issue by bklooste** [autumnai/collenchyma#56]
ben@benserver ~/src/collenchyma $ cargo build --no-default-features --features cuda
   Compiling collenchyma v0.0.8 (file:///home/ben/src/collenchyma)
src/frameworks/cuda/mod.rs:94:16: 94:42 error: irrefutable if-let pattern [E0162]
src/frameworks/cuda/mod.rs:94         if let &DeviceType::Cuda(ref ctx) = self.device() {

updated nightly and still happens 
rustc 1.9.0-nightly (b12b4e4e3 2016-03-17)

cargo build --features cuda   is ok
cargo build --no-default-features --features "cuda native" is ok   
cargo build --no-default-features --features "cuda opencl"  is ok with unused import warnings

**Comment by hobofan** [comment]
Yes, collenchyma doesn't work without the native feature right now.

Native is currently always required because it is the only way to get in/out of a SharedTensor. If we would have a way to create a SharedTensor from a CUDA/OpenCL memory pointer collenchyma could be used to compute something meaningful without the native framework.

Getting it to compile might not be too much work, and a PR fixing that would be appreciated.

**Comment by bklooste** [comment]
Had a look at it and its not trivial it basically means pulling out all native #feature from collenchyma  .. which does kind of make sense   if it needs it for tensor it should be there (and the other frameworks are moving to having some things run native some things run cuda)..  It then  need a empty   sync_out / context  for native because natice\cpu has synchin requires it on line 52 . 

I think the implications are a bit much  for a first PR as im still trying to understand how it all hangs together,
