### ISSUE TITLE
Finish BLAS library for Native, OpenCL and Cuda

### ISSUE THREAD

**Issue by MichaelHirn** [autumnai/collenchyma#6]
At the moment only the Native Framework has the Level1 Blas implementation.

Implementing it for the others as well would be a great step forward and should be completed with the completion of the other Frameworks for version 0.1.0.

**Comment by hobofan** [comment]
Since the issue was created plugins have been introduced and the BLAS functionality has been extracted into [this repository](https://github.com/autumnai/collenchyma-blas).

Progress on the implementation should be visible there once https://github.com/autumnai/collenchyma-blas/issues/5 has been resolved.
